VertexCraft/Models/Banner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VertexCraft.Models
{
    public class Banner
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string ImagePath { get; set; }
        public bool IsDelete { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

VertexCraft/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VertexCraft.Models;
using VertexCraft.ViewModel;

namespace VertexCraft.Controllers
{
    [Authorize]
    public class BannerController : Controller
    {
        // GET: Banner
        ApplicationDbContext db = new ApplicationDbContext();
        
        public ActionResult Index()
        {
            var category = db.Categories.Where(c => c.IsDeleted == false).ToList();
            var banner = db.Banners.Where(c=> c.IsDelete == false).ToList();
            List<BannerViewModel> bannerViewModels = new List<BannerViewModel>();
            foreach (var item in banner)
            {
                bannerViewModels.Add(new BannerViewModel() {
                    Id = item.Id,
                    Title = item.Title,
                    SubTitle = item.SubTitle,
                    ImagePath = item.ImagePath,
                    Category = category.FirstOrDefault(c=> c.Id == item.CategoryId)
                });
            }
            return View(bannerViewModels);
        }

        // GET: Banner/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var banner = db.Banners.FirstOrDefault(c => c.Id == id);
            var category = db.Categories.ToList();
            BannerViewModel bannerViewModel = new BannerViewModel()
            {
                Id = banner.Id,
                Title = banner.Title,
                SubTitle = banner.SubTitle,
                ImagePath = banner.ImagePath,
                Category = category.FirstOrDefault(c => c.Id == banner.CategoryId)
            };

            return View(bannerViewModel);
        }

        // GET: Banner/Create
        public ActionResult Create()
        {
            var category = db.Categories.Where(c=> c.IsDeleted == false).ToList();
            BannerViewModel bannerViewModel = new BannerViewModel()
            {
                Categories = category
            };
            return View(bannerViewModel);
        }

        // POST: Banner/Create
        [HttpPost]
        public ActionResult Create(BannerViewModel bannerViewModel)
        {
            try
            {

                if(bannerViewModel.Image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(bannerViewModel.Image.FileName);
                    string extension = Path.GetExtension(bannerViewModel.Image.FileName);
                    var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    fileName = Path.Combine(Server.MapPath("~/BannerImages/"), fileNames);
                    bannerViewModel.Image.SaveAs(fileName);

                    Banner banner = new Banner()
                    {
                        ImagePath = path,
                        Title = bannerViewModel.Title,
                        SubTitle = bannerViewModel.SubTitle,
                        CategoryId = bannerViewModel.CategoryId
                    };
                    db.Banners.Add(banner);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    Banner banner = new Banner()
                    {
                        Title = bannerViewModel.Title,
                        SubTitle = bannerViewModel.SubTitle,
                        ImagePath = bannerViewModel.ImagePath,
                        CategoryId = bannerViewModel.CategoryId
                    };
                    db.Banners.Add(banner);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }                
            }
            catch
            {
                return View();
            }
        }

        // GET: Banner/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var banner = db.Banners.FirstOrDefault(c => c.Id == id);
            var category = db.Categories.Where(c => c.IsDeleted == false).ToList();
            BannerViewModel bannerViewModel = new BannerViewModel()
            {
                Id = banner.Id,
                Title = banner.Title,
                SubTitle = banner.SubTitle,
                ImagePath = banner.ImagePath                
            };
            ViewBag.CategoryId = new SelectList(category, "Id", "Name", banner.CategoryId);
            return View(bannerViewModel);
        }

        // POST: Banner/Edit/5
        [HttpPost]
        public ActionResult Edit(BannerViewModel bannerViewModel)
        {
            try
            {
                if (bannerViewModel.Image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(bannerViewModel.Image.FileName);
                    string extension = Path.GetExtension(bannerViewModel.Image.FileName);
                    var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    fileName = Path.Combine(Server.MapPath("~/BannerImages/"), fileNames);
                    bannerViewModel.Image.SaveAs(fileName);

                    Banner banner = new Banner()
                    {
                        Id = bannerViewModel.Id,
                        Title = bannerViewModel.Title,
                        SubTitle = bannerViewModel.SubTitle,
                        ImagePath = path,
                        CategoryId = bannerViewModel.CategoryId
                    };
                    db.Entry(banner).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    Banner banner = new Banner()
                    {
                        Id = bannerViewModel.Id,
                        Title = bannerViewModel.Title,
                        SubTitle = bannerViewModel.SubTitle,
                        ImagePath = bannerViewModel.ImagePath,
                        CategoryId = bannerViewModel.CategoryId
                    };
                    db.Entry(banner).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var banner = db.Banners.FirstOrDefault(c => c.Id == id);
            banner.IsDelete = true;
            db.Entry(banner).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VertexCraft/Views/Banner/Create.cshtml
@model VertexCraft.ViewModel.BannerViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Banner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.Categories, "Id", "Name"), "Select Category", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SubTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
        </div>
    </div>


    @* image upload section start *@
    <div class="form-group">

        <div class="col-md-10">
            <div>
                <div>
                    <label>Upload Image</label>
                    <div id="imgPreview" class="thumbnail" style="display: block">
                        <img src="" class="img-responsive" id="targetImg" alt="Post Images" style="height: 250px; width: 300px;" />
                        <div class="caption">
                            <a href="#" onclick="ClearPreview()"><i class="glyphicon glyphicon-trash"></i></a>
                            <span id="description"></span>
                        </div>
                    </div>
                </div>
                <br />
                <div class="btn btn-primary ">
                    <div class="col-md-10">
                        <input type="file" name="Image" id="fileUpload" accept=".png,.jpg,.jpeg,.gif,.tif" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    @* image upload section end *@

    @*<div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>*@



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            debugger;
            $("#fileUpload").change(function () {
                debugger;
                var file = this.files;
                if (file && file[0]) {
                    ReadImage(file[0]);
                }
            });
        });
        var ReadImage = function (file) {
            debugger;
            var reader = new FileReader;
            var image = new Image;
            reader.readAsDataURL(file);
            reader.onload = function (_file) {
                image.src = _file.target.result;
                image.onload = function () {
                    var height = this.height;
                    var width = this.width;
                    var type = file.type;
                    var size = ~~(file.size / 1024) + "KB";
                    $("#targetImg").attr('src', _file.target.result);
                    $("#description").text("Size:" + size + ", " + height + "X " + width + ", " + type + "");
                    $("#imgPreview").show();
                };
            };
        };
        var ClearPreview = function () {
            debugger;
            $("#fileUpload").val('');
            $("#description").text('');
            $("#imgPreview").hide();
        };
    </script>
}

VertexCraft/Views/Banner/Details.cshtml
@model VertexCraft.ViewModel.BannerViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Url.Content("~/BannerImages/" + Model.ImagePath)" style="height: 80px; width: 80px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubTitle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VertexCraft/Views/Banner/Edit.cshtml
@model VertexCraft.ViewModel.BannerViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Banner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @*<div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SubTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <div>
                <div>
                    <label>Upload Image</label>
                    <div id="imgPreview" class="thumbnail" style="display: block">
                        <img src="@Url.Content("~/BannerImages/" + Model.ImagePath)" class="img-responsive" id="targetImg" alt="Post Images" style="height: 250px; width: 300px;" />
                        @Html.HiddenFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                        <div class="caption">
                            <a href="#" onclick="ClearPreview()"><i class="glyphicon glyphicon-trash"></i></a>
                            <span id="description"></span>
                        </div>
                    </div>
                </div>
                <br />
                <div class="btn btn-primary ">
                    <div class="col-md-10">
                        <input type="file" name="Image" id="fileUpload" accept=".png,.jpg,.jpeg,.gif,.tif" />
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            debugger;
            $("#fileUpload").change(function () {
                debugger;
                var file = this.files;
                if (file && file[0]) {
                    ReadImage(file[0]);
                }
            });
        });
        var ReadImage = function (file) {
            debugger;
            var reader = new FileReader;
            var image = new Image;
            reader.readAsDataURL(file);
            reader.onload = function (_file) {
                image.src = _file.target.result;
                image.onload = function () {
                    var height = this.height;
                    var width = this.width;
                    var type = file.type;
                    var size = ~~(file.size / 1024) + "KB";
                    $("#targetImg").attr('src', _file.target.result);
                    $("#description").text("Size:" + size + ", " + height + "X " + width + ", " + type + "");
                    $("#imgPreview").show();
                };
            };
        };
        var ClearPreview = function () {
            debugger;
            $("#fileUpload").val('');
            $("#description").text('');
            $("#imgPreview").hide();
        };
    </script>
}

VertexCraft/Views/Banner/Index.cshtml
@model IEnumerable<VertexCraft.ViewModel.BannerViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="card">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-bordered table-hover table-striped" id="myTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SubTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImagePath)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryId)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubTitle)
                </td>
                <td>
                    <img src="@Url.Content("~/BannerImages/" + item.ImagePath)" style="height: 80px; width: 80px;" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { onclick = "return confirm ('Are You Sure?? You Want To Delete!')" })
                </td>
            </tr>
            }
        </tbody>
    </table>

</div>