VertexCraft/Models/NewArrival.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VertexCraft.Models
{
    public class NewArrival
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FilePath { get; set; }
    }
}

VertexCraft/Controllers/NewArrivalsController.cs
using ImageResizer;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VertexCraft.Models;
using VertexCraft.ViewModel;

namespace VertexCraft.Controllers
{
    public class NewArrivalsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: NewArrivals
        public ActionResult Index()
        {
            return View(db.NewArrivals.ToList());
        }

        // GET: NewArrivals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewArrival newArrival = db.NewArrivals.Find(id);
            if (newArrival == null)
            {
                return HttpNotFound();
            }
            return View(newArrival);
        }

        // GET: NewArrivals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewArrivals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewArrivaleViewModel newArrivalViewModel)
        {
            if (ModelState.IsValid)
            {
                if (newArrivalViewModel.Image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(newArrivalViewModel.Image.FileName);
                    string extension = Path.GetExtension(newArrivalViewModel.Image.FileName);
                    var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    fileName = Path.Combine(Server.MapPath("~/NewArrivalImages/"), fileNames);
                    newArrivalViewModel.Image.SaveAs(fileName);
                    
                    //ResizeSettings imageResizer = new ResizeSettings()
                    //{
                    //    Width = 700,
                    //    Height = 398
                    //};
                    //ImageBuilder.Current.Build(fileName, fileName, imageResizer);

                    NewArrival newArrival = new NewArrival()
                    {
                        FilePath = path,
                        Title = newArrivalViewModel.Title
                    };
                    db.NewArrivals.Add(newArrival);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    NewArrival newArrival = new NewArrival()
                    {
                        FilePath = newArrivalViewModel.FilePath,
                        Title = newArrivalViewModel.Title
                    };
                    db.NewArrivals.Add(newArrival);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View();
        }

        // GET: NewArrivals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var newArrival = db.NewArrivals.FirstOrDefault(c => c.Id == id);
            NewArrivaleViewModel newArrivaleViewModel = new NewArrivaleViewModel()
            {
                Id = newArrival.Id,
                Title = newArrival.Title,
                FilePath = newArrival.FilePath
            };
            return View(newArrivaleViewModel);
        }

        // POST: NewArrivals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NewArrivaleViewModel newArrivalViewModel)
        {
            if (ModelState.IsValid)
            {
                if (newArrivalViewModel.Image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(newArrivalViewModel.Image.FileName);
                    string extension = Path.GetExtension(newArrivalViewModel.Image.FileName);
                    var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    fileName = Path.Combine(Server.MapPath("~/NewArrivalImages/"), fileNames);
                    newArrivalViewModel.Image.SaveAs(fileName);
                    

                    //ResizeSettings imageResizer = new ResizeSettings()
                    //{
                    //    Height = 398                        
                    //};
                    

                    //ImageBuilder.Current.Build(fileName, fileName, imageResizer);

                    NewArrival newArrival = new NewArrival()
                    {
                        Id = newArrivalViewModel.Id,
                        FilePath = path,
                        Title = newArrivalViewModel.Title
                    };
                    db.Entry(newArrival).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    NewArrival newArrival = new NewArrival()
                    {
                        Id = newArrivalViewModel.Id,
                        FilePath = newArrivalViewModel.FilePath,
                        Title = newArrivalViewModel.Title
                    };
                    db.Entry(newArrival).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        // GET: NewArrivals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewArrival newArrival = db.NewArrivals.Find(id);
            if (newArrival == null)
            {
                return HttpNotFound();
            }
            return View(newArrival);
        }

        // POST: NewArrivals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewArrival newArrival = db.NewArrivals.Find(id);
            db.NewArrivals.Remove(newArrival);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VertexCraft/Views/NewArrivals/Create.cshtml
@model VertexCraft.Models.NewArrival

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "NewArrivals", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Image" class="form-control" />
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VertexCraft/Views/NewArrivals/Delete.cshtml
@model VertexCraft.Models.NewArrival

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            <img src="@Url.Content("~/NewArrivalImages/" + Model.FilePath)" style="height: 80px; width: 80px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VertexCraft/Views/NewArrivals/Details.cshtml
@model VertexCraft.Models.NewArrival

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NewArrival</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            <img src="@Url.Content("~/NewArrivalImages/" + Model.FilePath)"/>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VertexCraft/Views/NewArrivals/Edit.cshtml
@model VertexCraft.ViewModel.NewArrivaleViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "NewArrivals", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content("~/NewArrivalImages/" + Model.FilePath)" style="height: 80px; width: 80px;" />
                <input type="file" name="Image" class="form-control" />
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VertexCraft/Views/NewArrivals/Index.cshtml
@model IEnumerable<VertexCraft.Models.NewArrival>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-hover table-striped" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilePath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <img src="@Url.Content("~/NewArrivalImages/" + item.FilePath)" style="height: 80px; width: 80px;" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>